### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ravern** [open-flash/rust-scoped-gc#1]
Hi there, thanks for this great project. Is this project still being updated/maintained?

**Comment by demurgos** [comment]
I havent't time to update it for some time, but this is still a project I'd like to maintain. I wrote it as part of an open source Flash Player implementation. I had to work on other parts of the player and left the VM on the side but once I'll get back to it, I'll update it.

It would be good to add documentation, CI, try to make it work on stable Rust, update the dependencies, etc. I'd be happy to grant you write access if you want to send some patches.

**Comment by ravern** [comment]
> this is still a project I'd like to maintain.

That's great!

> I'd be happy to grant you write access if you want to send some patches.

Sorry 😅, but I don't think I have the time to submit them. It's okay if you don't have time either, just wanted to inquire about the status of this project.

Thanks again 😬
